# @package _global_
defaults:
  - /trainer: default
  - /loader: default
  - /dataset: agc
  - /task: regression
  - /optimizer: adamw
  - /scheduler: cosine_warmup

task:
  torchmetrics: null
  metrics:
    - loss

train:
  monitor: val/loss
  mode: min
  ema: 5

encoder:
  - embedding
  - _name_: time

decoder:
  _name_: sequence
  mode: pool

trainer:
  max_epochs: 5
  val_check_interval: 0.2

optimizer:
  lr: 0.004
  weight_decay: 0.01

scheduler:
  num_warmup_steps: 500
  num_training_steps: 6000