_name_: agc
size:
    - 384
    - 96
    - 96
offset: 4
features: "S"
target: "filltime"
variant: 0
scale_raw: True
scale_meta: True
maxIT: 500
meta_features: True
timestep: 5
# freq: 'h'
__l_max: ${eval:${.size.0}+${.size.2}}


"size": None,
        "offset": 4,
        "target": "filltime",
        "variant": 0,
        "scale_raw": True,
        "scale_meta": True,
        "maxIT": 500,
        "meta_features": True,
        "timestep": 5,